name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Test
      run: |
        npm install
        npm run build
        npm test

    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: 18.190.117.184
        username: ec2-user
        key: ${{ secrets.aws_SECRET }}
        source: "build/"
        target: "/var/www/html"
